_wandb:
    value:
        cli_version: 0.19.8
        code_path: code/weave/pdf_summarizer/model.py
        m: []
        python_version: 3.11.4
        t:
            "1":
                - 55
                - 95
                - 97
                - 105
            "2":
                - 55
                - 95
                - 97
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.4
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
