_wandb:
    value:
        cli_version: 0.19.9
        code_path: code/model.py
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 49
                - 55
                - 95
            "2":
                - 49
                - 55
                - 95
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
